#!/bin/bash

# (c) Copyright 2021 Tor-Einar Skog NIBIO
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Managing downloading of weather data from MeteoFrance
# Getting the data, creating the NetCDF file
./meteofr.pl
# Copy data to the weather adapter folder
cp ./all.nc /opt/ipmdecisions/NetCDF-Location-Weather-Adapter/weather_data/
